title: Joojo Walker

description: I'm an Researcher and an Educator

logo: /assets/img/Joojo.jpg

author:
  name: Joojo Walker
  bio: I'm an Researcher and an Educator
  github: https://github.com/WorldChanger01
  linkedin: https://www.linkedin.com/in/joojo-walker-057b759a/
  twitter:
  url:

theme: jekyll-theme-minimal
